name: linStat

on: [push, pull_request, workflow_dispatch]

env:
  SETUP_PATH: .ci

jobs:
    container:
        name: ${{ matrix.name }}
        runs-on: ubuntu-latest
        container:
            image: ${{ matrix.image }}
        env:
            CMP: ${{ matrix.cmp }}
            BCFG: ${{ matrix.configuration }}
            BASE: ${{ matrix.base }}
            CI_CROSS_TARGETS: ${{ matrix.cross }}
            EXTRA: ${{ matrix.extra }}
        strategy:
            fail-fast: false
            matrix:
                include:
                - name: Debian 11
                  image: debian:11
                  cmp: gcc
                  configuration: default
                  base: "7.0"
                  # g++ 10.2.1 defaults to c++14
                  extra: "CMD_CXXFLAGS=-std=c++17"

                - name: Debian 12
                  image: debian:12
                  cmp: gcc
                  configuration: default
                  base: "7.0"

                - name: Fedora latest
                  image: fedora:latest
                  cmp: gcc
                  configuration: default
                  base: "7.0"

        steps:
        - name: System setup
          shell: bash
          run: |
            if type apt-get
            then
                apt-get update
                apt-get -y install git python3 build-essential
            elif type dnf
            then
                dnf install -y git python3 make perl gcc-c++ glibc-devel readline-devel ncurses-devel perl-devel
            fi
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: Prepare and compile dependencies
          run: python3 .ci/cue.py prepare
        - name: Build main module
          run: python3 .ci/cue.py build
